export const RABBITMQ_TICKETS_MICROSERVICE = 'RABBITMQ_TICKETS_MICROSERVICE';
export const RABBITMQ_AUTH_MICROSERVICE = 'RABBITMQ_AUTH_MICROSERVICE';
export const RABBITMQ_USERS_MICROSERVICE = 'RABBITMQ_USERS_MICROSERVICE';
export const RABBITMQ_REPORTS_MICROSERVICE = 'RABBITMQ_REPORTS_MICROSERVICE';
